;NAME:HAGER HOSNY 
;SEC:2
;BN :26



.MODEL SMALL
.STACK 64
.DATA 
WIN    DB "CONGRATULATION$"
LOST   DB  "SORRY TRY AGAIN $"
STARTX DW 10    ;بستخدمه وانا بعمل ال GRID
STARTY DW 10     ;بستخدمه وانا بعمل ال GRID
PACX   DB 8      ;بستخدمه ف رسم PACWOMAN
PACY   DB 6      ;بستخدمه ف رسم PACWOMAN    (X REFERS TO ROW & Y REFERS TO COLUMN (انا عكسساهم يعتبر ))
TEMP1  DW ?      ;بستخدمهم لو عندي بايت و هحولها ل ورد
TEMP2  DW ?
PACX2  DB 20    ;TEMP عشان لو محتاجه ال VALUE  قبل ما اعمل حاجه عرف ارجعها تاني 
PACY2  DB 11
MONX   DB 120  ;بستخدمهم ف ال MONSTERS
MONY   DB 93 
MONX2   DB 120  ;بستخدمهم ف ال MONSTERS
MONY2   DB 93 
MONSTEMP DB 93 
COINX  DB ?    ; الاماكن بتاعت ال HEARTS
COINY  DB  ?
COINCOLOR DB ?  
COINTEMP DB ?  
COUNT1  DB 14
COUNT2  DB 14
TX     DB ?
TY DB ?
TX3 DB ?
TY3 DB ?
SAVE DB ?
COLLECTED DB 0
TEMPCOLOR DB 12
MONSTERX1 DB 120
MONSTERY1 DB 93
MONSTERX2 DB  155 
MONSTERY2 DB 6 
MONSTERX3 DB 83 
MONSTERY3 DB 229 
MONSTERX4 DB 170 
MONSTERY4 DB 125
D1 DB 0
D2 DB 0
D3 DB 0
D4 DB 0
ACTION DB ?		;0 UP 1 DOWN 2 RIGHT 3 LEFT
HEART	DB     0,0,1,1,1,0,0,0,0,1,1,1,0,0
		DB     0,1,1,1,1,1,0,0,1,1,1,1,1,0
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     0,1,1,1,1,1,1,1,1,1,1,1,1,0
		DB     0,1,1,1,1,1,1,1,1,1,1,1,1,0
		DB     0,0,1,1,1,1,1,1,1,1,1,1,0,0
		DB     0,0,0,1,1,1,1,1,1,1,1,0,0,0
		DB     0,0,0,0,1,1,1,1,1,1,0,0,0,0
		DB     0,0,0,0,0,1,1,1,1,0,0,0,0,0
		DB     0,0,0,0,0,0,1,1,0,0,0,0,0,0
		
PACMANGRID 	DB 0,0,0,2,2,0,0,0,0,0,0,0,0,0
		DB     0,0,0,2,2,2,1,1,1,1,0,0,0,0
		DB     0,0,2,3,2,2,1,1,1,1,1,1,0,0
		DB     2,2,3,2,1,1,1,1,1,1,1,1,1,0
		DB     2,2,2,1,1,1,1,1,1,1,1,1,1,0
		DB     0,2,2,1,1,1,1,1,1,0,0,0,0,0
		DB     0,1,1,1,1,1,1,0,0,0,0,0,0,0
		DB     0,1,1,1,1,0,0,0,0,0,0,0,0,0
		DB     0,1,1,1,1,1,1,0,0,0,0,0,0,0
		DB     0,1,1,1,1,1,1,1,1,0,0,0,0,0
		DB     0,0,1,1,1,1,1,1,1,1,1,1,1,0
		DB     0,0,1,1,1,1,1,1,1,1,1,1,1,0
		DB     0,0,0,0,1,1,1,1,1,1,1,0,0,0
		DB     0,0,0,0,0,0,1,1,1,0,0,0,0,0
		
MONSTER	DB     0,0,0,0,0,1,1,1,1,0,0,0,0,0
		DB     0,0,0,1,1,1,1,1,1,1,1,0,0,0
		DB     0,0,1,1,1,1,1,1,1,1,1,1,0,0
		DB     0,1,1,1,2,2,1,1,1,1,2,2,1,0
		DB     0,1,1,2,2,2,2,1,1,2,2,2,2,0
		DB     0,1,1,2,2,3,3,1,1,2,2,3,3,0
		DB     1,1,1,2,2,3,3,1,1,2,2,3,3,1
		DB     1,1,1,1,2,2,1,1,1,1,2,2,1,1
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     1,1,1,1,1,1,1,1,1,1,1,1,1,1
		DB     1,1,0,1,1,1,0,0,1,1,1,0,1,1
		DB     1,0,0,0,1,1,0,0,1,1,0,0,0,1

		
		
				
		
TX1 DW ?
TX2 DW ?
TY1 DW ?
TY2 DW ?

.CODE
;-----------------SETCURSOR----------------------------
SETCURSOR MACRO X,Y
MOV AH,2 
MOV DL,y
MOV DH,x
MOV BX,0
INT 10H
ENDM
;-----------------
;-----------------PRINT SINGLECHAR----------------------
PRINTCHAR MACRO CHAR
MOV AH,2
MOV DL,CHAR
MOV BX,0
INT 21H
ENDM
;----------------PRINTCHAR-------------------------------

 
;-------DRAWPIXEL---------------------------
DRAWPIXEL MACRO X,Y,COLOR
    MOV CX,Y ;COLUMN
	MOV DX,X;ROW
	MOV AL,COLOR;PIXEL COLOR
	MOV AH,0CH ;DRAW PIXEL COMMAND
	MOV BH,0
	INT 10H
ENDM
;------------END OF DRAWPIXEL --------------
;---------SET-------------------
SET MACRO X1,Y1,X2,Y2
MOV AX,X1
	MOV TX1,AX
	MOV AX,X2
	MOV TX2,AX
	MOV AX,Y1
	MOV TY1,AX
	MOV AX,Y2
	MOV TY2,AX
ENDM

;---------RECTANGLE-------------------------
RECTANGLE MACRO X1,Y1,X2,Y2,COLOR
LOCAL OUTLOOP,INLOOP
MOV CX,Y1 ;COLUMN
	MOV DX,X1;ROW
	MOV AL,COLOR ;PIXEL COLOR
	MOV AH,0CH ;DRAW PIXEL COMMAND
	MOV BH,0
OUTLOOP: INT 10H   ;DRAW THE BLOCK  ---
                                ; ---
								; ---
								; ---
								; ---
      
INLOOP:
    
    INC CX        ;DRAW HORIZONTAL LINE ---
	INT 10H
	CMP CX,Y2
	JNZ INLOOP     ;END OF ---
	
	MOV CX,Y1     ;TO RETURN TO THE PREVIOUS POINT    
	INC DX
	CMP DX,X2
	JNZ OUTLOOP

ENDM
;-------END OF RECTANGLE --------------------------
;---------------------SETCOIN---------------------
SETCOIN MACRO X,Y,COLOR
MOV AL,X  
MOV COINX,AL            ;بعمل SWAP 
MOV AL,Y
MOV COINY,AL           ;بحط ال VALUE الجديده ال عاوزة اوديه عندها
MOV COINTEMP,AL        ; ديه انا بستخدمها ف رسم الكوين فببقا محتاجها كحاجه متخزنه عشان لما احتجها تاني 
MOV AL,COLOR
MOV COINCOLOR,AL
ENDM
;---------------------SETCOIN---------------------
;---------------------SETMONSTERS---------------------
SETMONSTERS MACRO X,Y
MOV AL,X                           ; هما بغير ف ال X,Y بتوع الوحوش
MOV MONX,AL
MOV AL,Y
MOV MONY,AL
MOV MONSTEMP,AL

ENDM
;---------------------SETMONSTERS---------------------
;-----------------------------------------------------------------------------------------------------------
;-                                        START OF MAIN                                                    -
;-----------------------------------------------------------------------------------------------------------

MAIN PROC FAR 
    MOV AX,@DATA 
    MOV DS,AX 
	
	CALL CLEAR
	CALL GRAPHIICSMODE
	CALL BORDER
	CALL FILL
   
	
	CALL MONSTERS    
	SETMONSTERS 114,145       ; برسم الاماكن بتاعت الوحوش ف الاول
	CALL MONSTERS             ; ديه الفانكشن ال بترسمهم
	SETMONSTERS 114,164
	CALL MONSTERS
	SETMONSTERS 114,182
	CALL MONSTERS
	
	CALL MAZE                 ;  كبرسم ال MAZE
	CALL SETXY                ;ديه فانكشن بتخزن القيمه عشان لما احتججها تاني
	CALL PACMAN               ; برسم باكمان
	CALL SETXY2               ; هنا انا برجعها عشان انا دايما محتاجه ال TOP LEFT  والفانكشن بتغيرهم جوا 30
	
    SETCOIN 7,150,4            ; بظبط الاماكن بتاعت القلوب والالوان بتاعتها و ارسمها
	CALL COINS
	SETCOIN 180,7,10
	CALL COINS
	SETCOIN 70,50,13
	CALL COINS
	SETCOIN 180,230,5
	CALL COINS
	SETCOIN 170,140,15
	CALL COINS
	CALL OPEN1
	CALL MOVE1              ; دول شويه ANIMATION ف الاول

	CALL MOVE2

	CALL MOVE3
; ديه ال الووب ال هفضل فيها ع طول 
GAMELOOP:
    MOV AL,MONSTERX1      ; بنقل اول وحش لل AX
	MOV AH,MONSTERY1
	CMP AL,19          ;اقصي قيمه المفروض يوصلها ف الحركه بتاعته لو وصل يبقي هغير اتجاه الحره 
	JBE SETMONSTER1T
	MOV BL,D1          ; بعرف اتجاه الحركه اتغير ولا لا 
    CMP BL,1
	JZ SETMONSTER1T
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS   ; همسح القديم
	CALL SETXYM2         ; برجع القيم ال انا حفظتها
	
	MOV AL,MONX
	SUB AL,14            ; بطرح عشان احركه لفوق
	MOV MONSTERX1,AL      
	MOV MONX,AL
	CALL MONSTERS        ; ابدا ارسمه ف المكان الجديد
	CALL DELAY
	;CALL SETXYM2
	
	;CALL SETM1
	
	 MOV AL,MONSTERX2
	MOV AH,MONSTERY2
	CMP AL,20
	JBE SETMONSTER2T
	MOV BL,D2
    CMP BL,1
	JZ SETMONSTER2T
	MOV MONX,AL
	MOV MONY,AH                             ; انا بكرر نفس ال فوق مع باقي monsters 
	CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	
	MOV AL,MONX
	SUB AL,14
	MOV MONSTERX2,AL
	MOV MONX,AL
	CALL MONSTERS
	CALL DELAY        ;دي انا ببطء فيها الحركه شويه 
	JMP C1
SETMONSTER1T:JMP SETMONSTER1
C1:	 
   MOV AL,MONSTERX3
	MOV AH,MONSTERY3
	CMP AL,19
	JBE SETMONSTER3T
	MOV BL,D3
    CMP BL,1
	JZ SETMONSTER3T
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	
	MOV AL,MONX
	SUB AL,14
	MOV MONSTERX3,AL
	MOV MONX,AL
	CALL MONSTERS
	CALL DELAY
	JMP C2
SETMONSTER2T:JMP SETMONSTER2
C2:
	 MOV AL,MONSTERX4
	MOV AH,MONSTERY4
	CMP AL,19
	JBE SETMONSTER4T
	MOV BL,D4
    CMP BL,1
	JZ SETMONSTER4T
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	
	MOV AL,MONX
	SUB AL,14
	MOV MONSTERX4,AL
	MOV MONX,AL
	CALL MONSTERS
JMP CONTINUE 
SETMONSTER4T:JMP SETMONSTER4
SETMONSTER3T:JMP SETMONSTER3
SETD11:JMP SETD1


; من اول هنا انا بكمل باقي الحركه بتاعته بس و هو نازل 
SETMONSTER1:
    MOV BL,1
	MOV D1,BL     ; بغيرها عشان لما اسال عليها فوق 
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS 
	CALL SETXYM2
	
	MOV AL,MONX
	ADD AL,14
	MOV MONX,AL
	MOV MONSTERX1,AL
	
	CALL SETXYM
	CALL DELAY
	CALL MONSTERS
	CALL DELAY
	CALL SETXYM2
	MOV AL,MONX
	CMP AL,150 
	JAE SETD11
	
	;CALL SETXYM2
	
	
	JMP CONTINUE 
; بكرر نفس الكلام ال فوق مع الباقي 
SETMONSTER2:
  MOV BL,1
	MOV D2,BL              
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	
	MOV AL,MONX
	ADD AL,14
	MOV MONX,AL
	MOV MONSTERX2,AL
	
	CALL SETXYM
	CALL DELAY
	CALL MONSTERS
	CALL DELAY
	CALL SETXYM2
	MOV AL,MONX
	CMP AL,150 
	JAE SETD2T
	JMP CONTINUE 

SETMONSTER3:
 MOV BL,1
	MOV D3,BL
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	
	MOV AL,MONX
	ADD AL,14
	MOV MONX,AL
	MOV MONSTERX3,AL
	
	CALL SETXYM
	CALL DELAY
	CALL MONSTERS
	CALL DELAY
	CALL SETXYM2
	MOV AL,MONX
	CMP AL,150
	JAE SETD3
	JMP CONTINUE 
SETD2T:JMP SETD2
SETMONSTER4:
     MOV BL,1
	MOV D4,BL
	MOV MONX,AL
	MOV MONY,AH
	CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	
	MOV AL,MONX
	ADD AL,14
	MOV MONX,AL
	MOV MONSTERX4,AL
	
	CALL SETXYM
	CALL DELAY
	CALL MONSTERS
	CALL DELAY
	CALL SETXYM2
	MOV AL,MONX
	CMP AL,150 
	JAE SETD4
	JMP CONTINUE 
	; الاربعه labels الجايين كل ال بيعملوه انهم بيغيره ال D عشان لما اجي اسال عنهم فوق 
SETD1:
MOV BL,0
MOV D1,BL
JMP CONTINUE 
SETD2:
MOV BL,0
MOV D2,BL
JMP CONTINUE 
SETD3:
MOV BL,0
MOV D3,BL
JMP CONTINUE 
SETD4:
MOV BL,0
MOV D4,BL
CONTINUE:		
	MOV AL,PACX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,PACY
	MOV TEMP2,AX
	
	CALL GETINPUT  ; ببدا اخد input 
	;HERE I WILL DETERMINE ACTION 
	CMP AH,72     ;UP
	JZ UP
	CMP AH,80     ;DOWN
	JZ DOWN
	CMP AH,75     ;LEFT
	JZ LEFT2
	CMP AH,77    ;RIGHT
	JZ RIGHTT    
    JMP GAMELOOP

DOWN:

	CALL SETXY       ;عشان ارجعها 
	CALL CLEARPACMAN ; امسح
	CALL SETXY2      ; ارجع
	
	CALL READPIXEL   ; هنا انا ببدا اعرف البيكسل ددي لونها ايه متوضحه تحت 
	MOV AH,1
	MOV ACTION,AH     ; بستخدمها عشان اعرف انا دوست زرار ايه 
	
	
	
	CMP AL,12
	JZ SAME2
	CMP AL,1
	JZ SAME2
	CMP AL,4     ; دول الوان القلوب لو خبط ف حاجه منهم هزود 1 لحد ما يجمع 5 يكسب 
	JZ COLLECT2
	 CMP AL,10
	JZ COLLECT2
    CMP AL,13
	JZ COLLECT2
    CMP AL,5
	JZ COLLECT2	
	CMP AL,15
	JZ COLLECT2	
	CMP AL,11
	JZ EXITLT2
    MOV AL,PACX
	ADD AL,7
	MOV PACX,AL
	

	CALL SETXY
	CALL PACMAN
	CALL SETXY2
	JMP GAMELOOP

LEFT2:JMP LEFT
RIGHTT:
    JMP RIGHT
UP:

    CALL SETXY
	CALL CLEARPACMAN
	CALL SETXY2
	
	MOV AH,0
	MOV ACTION,AH
	CALL READPIXEL
	
	CMP AL,12
	JZ SAME2
	CMP AL,1
	JZ SAME2
	CMP AL,4 
	JZ COLLECT2
	 CMP AL,10
	JZ COLLECT2
    CMP AL,13
	JZ COLLECT2
    CMP AL,5
	JZ COLLECT2	
	CMP AL,15
	JZ COLLECT2
CMP AL,3
	JZ EXITLT2	
	 MOV AL,PACX
	SUB AL,7
	MOV PACX,AL
	CALL SETXY
	CALL PACMAN
	CALL SETXY2
	JMP GAMELOOP

EXITLT2:JMP EXITLT
SAME2:JMP SAME
COLLECT2:JMP COLLECT
LEFT:

    CALL SETXY
	CALL CLEARPACMAN
	CALL SETXY2
	
	MOV AH,3
	MOV ACTION,AH
	CALL READPIXEL
	
	CMP AL,12
	JZ SAME
	CMP AL,1
	JZ SAME
	CMP AL,4 
	JZ COLLECT
	 CMP AL,10
	JZ COLLECT 
    CMP AL,13
	JZ COLLECT
    CMP AL,5
	JZ COLLECT	
	CMP AL,15
	JZ COLLECT
CMP AL,3
	JZ EXITLT	
	 MOV AL,PACY
	SUB AL,7
	MOV PACY,AL
	CALL SETXY
	CALL PACMAN
	CALL SETXY2
	JMP GAMELOOP
RIGHT:
 
    CALL SETXY
	CALL CLEARPACMAN
	CALL SETXY2
	
	MOV AH,2
	MOV ACTION,AH
	CALL READPIXEL
	
	CMP AL,12
	JZ SAME
	CMP AL,1
	JZ SAME
	CMP AL,4 
	JZ COLLECT
	 CMP AL,10
	JZ COLLECT 
    CMP AL,13
	JZ COLLECT
    CMP AL,5
	JZ COLLECT	
	CMP AL,15
	JZ COLLECT	
	CMP AL,3 
	JZ EXITLT
	 MOV AL,PACY
	ADD AL,7
	MOV PACY,AL
	CALL SETXY
	CALL PACMAN
	CALL SETXY2
	JMP GAMELOOP
SAME:
     CALL SETXY
	CALL PACMAN 
	CALL SETXY2
    JMP GAMELOOP
EXITLT:JMP EXITL
COLLECT :
    CMP AL,4
	JZ HEART1
	CMP AL,10
	JZ HEART2
	CMP AL,13
	JZ HEART3
	CMP AL,5
	JZ HEART4
	CMP AL,15
	JZ HEART5
BCK:	
   INC COLLECTED 
	MOV AL,5
	CMP AL,COLLECTED
	JZ EXIT
	JMP SAME
 HEART1:SETCOIN 7,150,4   ; هنا بمسح القلب ال هو كله 
	CALL CLEARCOINS
	JMP GAMELOOP
HEART2:	SETCOIN 180,7,10
	CALL CLEARCOINS
	JMP GAMELOOP
HEART3:	SETCOIN 70,50,13
CALL CLEARCOINS
	JMP GAMELOOP
HEART4:	SETCOIN 180,230,5
	CALL CLEARCOINS
	JMP GAMELOOP
HEART5:	SETCOIN 170,140,15
	CALL CLEARCOINS
	JMP GAMELOOP
EXIT:CALL CLEAR
    SETCURSOR 10,10 
	CALL WINP
	JMP ENDGAME
EXITL:	
	CALL CLEAR
    SETCURSOR 10,10 
	CALL LOSE
	JMP ENDGAME
ENDGAME:
	MOV AH,4CH
	INT 21H 
	MAIN ENDP
	

;-----------------CLEAR------------------------------------	
CLEAR PROC 
     MOV AX,0600H      ; بستخدمها عشان امسح الشاشه 
	 MOV BH,07
	 MOV CX,0
	 MOV DX,184FH
	 INT 10H
	RET 
CLEAR ENDP
;----------------CLEAR-------------------------------------

;--------------GRAPHICSMODE-------------------------------
GRAPHIICSMODE PROC 
     MOV AH,0             ; بحول الموود
     MOV AL,13H
     INT 10H
	 RET
GRAPHIICSMODE ENDP	 
;---------------GRAPHICSMODE-------------------------------

;--------START OF BORDER--------------------------------	
BORDER PROC
;DRAW THE TOP HORIZONTALL LINE 
RECTANGLE 0,0,3,250,1

;DRAW THE BOTTOM HORIZONTALL LINE 
RECTANGLE 197,0,200,250,1

;DRAW THE LEFT HORIZONTALL LINE 
	RECTANGLE 0,0,200,2,1
;DRAW THE RIGHT HORIZONTALL LINE 

	RECTANGLE 0,247,70,250,1
	RECTANGLE 100,247,205,250,1
	
;----------BORDER-------------------
	SET 0,0,0,250
	CALL HORIZONTAL
	SET 3,3,3,247
	CALL HORIZONTAL
	SET 196,3,196,247
	CALL HORIZONTAL
	SET 199,0,199,250
	CALL HORIZONTAL               ; دول عشان ارسم الحاجات البينك ال ع البوردر
	SET 0,0,200,0600H
	CALL VERTICAL
	SET 3,3,197,3
	CALL VERTICAL
	SET 3,247,70,247
	CALL VERTICAL
	SET 0,250,70,250
	CALL VERTICAL
	SET 100,247,197,247
	CALL VERTICAL
	SET 100,250,200,100
	CALL VERTICAL
RET
BORDER ENDP	
;-----------BORDER--------------------------------
;-----------------MAZE-----------------------------	
MAZE PROC 
; THIS IS OUR RECTANGLE TO PROVIDE THE MAZE
	RECTANGLE 30,20,60,24,1
	SET 30,20,60,20
	CALL VERTICAL
	SET 29,21,29,25
	CALL HORIZONTAL
	SET 30,25,60,25
	CALL VERTICAL
	SET 60,21,60,25
	CALL HORIZONTAL
	
	RECTANGLE 90,20,120,24,1
	SET 90,20,120,20
	CALL VERTICAL
	SET 89,21,89,24
	CALL HORIZONTAL
	SET 90,24,120,24
	CALL VERTICAL
	SET 120,21,120,24
	CALL HORIZONTAL
	
	RECTANGLE 150,30,154,80,1
	SET 154,30,154,81
	CALL HORIZONTAL
	SET 150,29,154,29
	CALL VERTICAL
	SET 149,30,150,45
	CALL HORIZONTAL
	SET 149,50,149,81
	CALL HORIZONTAL
	
	RECTANGLE 120,45,150,49,1
	SET 120,45,150,45
	CALL VERTICAL
    SET 119,46,118,50
	CALL HORIZONTAL
	SET 120,50,150,50
	CALL VERTICAL
	SET 150,81,154,81
	CALL VERTICAL
	
	RECTANGLE 175,30,198,34,1
	SET 175,30,197,30
	CALL VERTICAL
	SET 174,31,174,34
	CALL HORIZONTAL
	SET 175,34,197,34
	CALL VERTICAL

	RECTANGLE 30,50,34,85,1
	SET 29,50,29,85
	CALL HORIZONTAL
	SET 34,50,34,85
	CALL HORIZONTAL
	SET 30,49,34,49
	CALL VERTICAL
	SET 30,85,34,85
	CALL VERTICAL
	
	
	RECTANGLE 60,50,64,85,1
    SET 59,50,59,85
	CALL HORIZONTAL
	SET 64,50,64,85
	CALL HORIZONTAL
	SET 60,49,64,49
	CALL VERTICAL
	SET 60,85,64,85
	CALL VERTICAL
	
	RECTANGLE 90,50,94,85,1
	SET 89,50,89,89
	CALL HORIZONTAL
	SET 94,50,94,85
	CALL HORIZONTAL
	SET 90,49,94,49
	CALL VERTICAL
  
	
	RECTANGLE 90,85,120,89,1
	SET 95,84,120,85
	CALL VERTICAL
	SET 90,89,120,89
	CALL VERTICAL
	SET 120,85,120,89
	CALL HORIZONTAL
	
    
	
    RECTANGLE 110,115,160,120,1
    SET 110,115,160,115
    CALL VERTICAL
    SET 110,120,160,120	
	CALL VERTICAL
	SET 109,116,109,120
	CALL HORIZONTAL
	SET 160,116,160,120
	CALL HORIZONTAL
	 
	RECTANGLE 30,115,80,120,1
	SET 30,115,80,115
    CALL VERTICAL
    SET 30,120,80,120	
	CALL VERTICAL
	SET 29,116,29,120
	CALL HORIZONTAL
	SET 80,116,80,120
	CALL HORIZONTAL
	 
	RECTANGLE 2,170,45,174,1
	SET 3,170,45,170
	CALL VERTICAL
	SET 3,174,45,174
	CALL VERTICAL
	SET 45,171,45,174
	CALL HORIZONTAL
	
	RECTANGLE 65,145,69,200,1
	SET 65,145,65,201
	CALL HORIZONTAL
	SET 69,145,69,201
	CALL HORIZONTAL
	SET 66,144,69,144
	CALL VERTICAL
	SET 66,201,69,201
	CALL VERTICAL
	
	;-----BOX------------
	RECTANGLE 95,140,97,200,1
	SET 94,140,94,204
	CALL HORIZONTAL
	SET 97,140,97,200
	CALL HORIZONTAL
	RECTANGLE 130,140,132,200,1
	SET 129,140,129,200
	CALL HORIZONTAL
	SET 132,140,133,204
	CALL HORIZONTAL
	RECTANGLE 95,140,130,142,1
	SET 95,140,132,140
	CALL VERTICAL
	SET 97,143,130,143
	CALL VERTICAL
	RECTANGLE 95,200,132,202,1
	SET 97,200,130,200
	CALL VERTICAL
	SET 95,203,132,203
	CALL VERTICAL
	RECTANGLE 94,160,98,180,4
	;-------BOX-----------------
	
	RECTANGLE 160,145,164,200,1
	SET 160,145,160,201
	CALL HORIZONTAL
	SET 164,145,164,201
	CALL HORIZONTAL
	SET 161,144,164,144
	CALL VERTICAL
	SET 161,201,164,201
	CALL VERTICAL

	
	RECTANGLE 110,220,160,225,1
    SET 110,220,160,220
    CALL VERTICAL
    SET 110,225,160,225
	CALL VERTICAL
	SET 109,221,109,225
	CALL HORIZONTAL
	SET 160,221,160,225
	CALL HORIZONTAL
	 
	RECTANGLE 30,220,80,225,1
	SET 30,220,80,220
    CALL VERTICAL
    SET 30,225,80,225	
	CALL VERTICAL
	SET 29,221,29,225
	CALL HORIZONTAL
	SET 80,221,80,225
	CALL HORIZONTAL
	
	
	RET
MAZE ENDP	
;-----------MAZE-----------------------
;--------------------------FILL-----------------------------
FILL PROC
LOOP1:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 15 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,190                  ; THE END OF THE ROW
	JBE LOOP1 

   	MOV BX,10
	MOV STARTX,BX
	MOV STARTY,BX
LOOP2:
    MOV BX,STARTY                ;TO ADD 	15 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,150                   ; THE END OF THE ROW
	JBE LOOP2 
	
	MOV BX,10
	MOV STARTX,BX
	MOV BX,160
	MOV STARTY,BX

LOOP3:
 MOV BX,STARTY                ;TO ADD 	5 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,220                   ; THE END OF THE ROW
	JBE LOOP3
	
	MOV BX,10
	MOV STARTX,BX
	MOV BX,40
	MOV STARTY,BX

LOOP4:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 15 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,150                  ; THE END OF THE ROW
	JBE LOOP4
	
    MOV BX,55
	MOV STARTX,BX
	MOV BX,10
	MOV STARTY,BX

LOOP5:
     MOV BX,STARTY                ;TO ADD 15 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,30                  ; THE END OF THE ROW
	JBE LOOP5	
	
	MOV BX,70
	MOV STARTX,BX
	MOV BX,10
	MOV STARTY,BX

LOOP6:
     MOV BX,STARTY                ;TO ADD 15 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,90              ; THE END OF THE ROW
	JBE LOOP6
	
	MOV BX,115
	MOV STARTX,BX
	MOV BX,10
	MOV STARTY,BX

LOOP7:
     MOV BX,STARTY                ;TO ADD 15 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,30                  ; THE END OF THE ROW
	JBE LOOP7
	
    MOV BX,130
	MOV STARTX,BX
	MOV BX,10
	MOV STARTY,BX

LOOP8:
     MOV BX,STARTY                ;TO ADD 8 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,30                  ; THE END OF THE ROW
	JBE LOOP8
	
	 MOV BX,160
	MOV STARTX,BX
	MOV BX,10
	MOV STARTY,BX

LOOP9:
    DRAWPIXEL STARTX,STARTY,14 
    
LOOP10:	
	
	MOV BX,STARTX                ;TO GET THE NEXT ROW
	ADD BX,15                     ;ADDING 8 TO GET THE NEXT ROW
	MOV STARTX,BX                ;EXCHNAGE THE STARTX TO CONTINUE AFTER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	CMP BX,175                 ;IF STARTX<=190 IT WILL CONTINUE TO DRAW THE NEXT ROW OTHERWISE WE ARRIVE TO THE END OF FILLING
	JBE LOOP10
    
	 MOV BX,160
	MOV STARTX,BX
	MOV BX,STARTY                ;TO ADD 8 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION

	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,235                 ; THE END OF THE ROW
	JBE LOOP9
	
	MOV BX,10
	MOV STARTX,BX
	MOV BX,STARTY
	SUB BX,15
	MOV STARTY,BX
	
LOOP11:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,150                  ; THE END OF THE ROW
	JBE LOOP11
	
	
	MOV BX,10
	MOV STARTX,BX
	MOV BX,100
	MOV STARTY,BX
	
LOOP12:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,150                  ; THE END OF THE ROW
	JBE LOOP12
	
    MOV BX,10
	MOV STARTX,BX
	MOV BX,130
	MOV STARTY,BX
	
LOOP13:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,150                  ; THE END OF THE ROW
	JBE LOOP13

    MOV BX,10
	MOV STARTX,BX
	MOV BX,145
	MOV STARTY,BX
	
LOOP14:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,60                 ; THE END OF THE ROW
	JBE LOOP14
	
	
    MOV BX,10
	MOV STARTX,BX
	MOV BX,160
	MOV STARTY,BX
	
LOOP15:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,60                 ; THE END OF THE ROW
	JBE LOOP15
	
	
    MOV BX,10
	MOV STARTX,BX
	MOV BX,205
	MOV STARTY,BX
	
LOOP16:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,60                 ; THE END OF THE ROW
	JBE LOOP16
	
	
    MOV BX,10
	MOV STARTX,BX
	MOV BX,190
	MOV STARTY,BX
	
LOOP17:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,60                 ; THE END OF THE ROW
	JBE LOOP17
	
	MOV BX,40
	MOV STARTX,BX
	MOV STARTY,BX

LOOP18:
    MOV BX,STARTY                ;TO ADD 8 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTY,BX                ;EXCHNAGE THE VALUE ATER ADDITION
	DRAWPIXEL STARTX,STARTY,14   ; DRAW THE CURRENT PIXWL IN THE SAME ROW
	MOV BX,STARTY                ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,75                 ; THE END OF THE ROW
	JBE LOOP18
	
	MOV BX,90
	MOV STARTX,BX
	MOV BX,70
	MOV STARTY,BX

LOOP19:
    DRAWPIXEL STARTX,STARTY,14
	MOV BX,STARTX               ;TO ADD 18 FOR THE VALUE (TO GET THE NEXT POINT IN THE ROW)
	ADD BX,15
	MOV STARTX,BX                ;EXCHNAGE THE VALUE AFTER ADDITION
	MOV BX,STARTX               ;TO SURE THAT BX HAVE THE SAME VALUE OF STARTY
	CMP BX,140                ; THE END OF THE ROW
	JBE LOOP19
RET
FILL ENDP

;---------COINS----------------
COINS PROC
 
      MOV DI,OFFSET HEART
LOP1H:
      MOV AL,[DI]  
      CMP AL,1         ; كل رقم ف الجريد انا بلونه بلون معين فهنا هفضل اسال عن الالوان دي عشان ارسمهم صح
      JZ LBL1H
      JMP LBL2H	  
CONT2H: 

      MOV CL,COUNT2     ; دي 2 لووب جوا بعض عشان ارسم الجريد 
      CMP CL,0
      JZ  EXIT2H 
      INC DI
      DEC COUNT1
      MOV AL,COUNT1
      CMP AL,0
      JZ  MOVEH
      JMP LOP1H
LBL1H:
MOV AL,COINX
	MOV AH,0               ; ببدل عشان ارسم 
	MOV TEMP1,AX
	MOV AL,COINY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,COINCOLOR;PIXEL COLOR         ;draw pixel fn
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC COINY
JMP CONT2H

LBL2H:
MOV AL,COINX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,COINY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,0;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC COINY
JMP CONT2H
MOVEH: 
    DEC COUNT2
    MOV AL,14
	MOV COUNT1,AL
    INC COINX
    MOV AL,COINTEMP
    MOV COINY,AL
    JMP LOP1H

EXIT2H:
MOV AX,14
MOV COUNT1,14
MOV COUNT2,14          ; برجع الcounters تاني
	
RET 
COINS ENDP	
;---------END OF COINS---------

;---------CLEARCOINS----------------
CLEARCOINS PROC
 
      MOV DI,OFFSET HEART
LOP1HC:
      MOV AL,[DI]
      JMP LBLHC	  
CONT2HC: 
                                 ; دي زي ال فوق بالظبط الفرق اني برسمهم كلهم اسود
      MOV CL,COUNT2
      CMP CL,0
      JZ  EXIT2H 
      INC DI
      DEC COUNT1
      MOV AL,COUNT1
      CMP AL,0
      JZ  MOVEHC
      JMP LOP1HC


LBLHC:
MOV AL,COINX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,COINY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,0;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC COINY
JMP CONT2HC
MOVEHC: 
    DEC COUNT2
    MOV AL,14
	MOV COUNT1,AL
    INC COINX
    MOV AL,COINTEMP
    MOV COINY,AL
    JMP LOP1HC

EXIT2HC:
MOV AX,14
MOV COUNT1,14
MOV COUNT2,14
	
RET 
CLEARCOINS ENDP	
;---------END OF CLEAR COINS---------

;--------MONSTERS--------------
MONSTERS PROC 
  ;HERE I WILL JUST DRAW THE RED RECTANGLES WHICH REFERS TO MONSTERS 
       MOV DI,OFFSET MONSTER
	  JMP LOP1M
  LBL3M:
    MOV AL,MONX
	MOV AH,0
	MOV TEMP1,AX                         ; نفس فكره القلوب مش مغره حاجه غير الالوان والكود كوبي من الفوق
	MOV AL,MONY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,0;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC MONY
JMP CONT2M

  LBL4M:
    MOV AL,MONX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,MONY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,1;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC MONY
JMP CONT2M 
LOP1M:
      MOV AL,[DI]
      CMP AL,1
      JZ LBL1M
	  CMP AL,2
      JZ LBL2M
	  CMP AL,3
	  JZ LBL4M
      JMP LBL3M  
CONT2M: 

      MOV CL,COUNT2
      CMP CL,0
      JZ  EXIT2M 
      INC DI
      DEC COUNT1
      MOV AL,COUNT1
      CMP AL,0
      JZ  MOVEM
      JMP LOP1M
LBL1M:
MOV AL,MONX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,MONY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,3;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC MONY
JMP CONT2M

LBL2M:
MOV AL,MONX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,MONY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,15;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC MONY
JMP CONT2M
MOVEM: 
    DEC COUNT2
    MOV AL,14
	MOV COUNT1,AL
    INC MONX
    MOV AL,MONSTEMP
    MOV MONY,AL
    JMP LOP1M

EXIT2M:
MOV AX,14
MOV COUNT1,14
MOV COUNT2,14
	
  RET 
  MONSTERS ENDP
 ;-------MONSTERS------------------------------
 
;--------CLEARMONSTERS--------------
CLEARMONSTERS PROC 
  ;HERE I WILL JUST DRAW THE RED RECTANGLES WHICH REFERS TO MONSTERS 
       MOV DI,OFFSET MONSTER

LOP1MC:
      MOV AL,[DI]

      JMP LBL1MC
	 
CONT2MC: 

      MOV CL,COUNT2
      CMP CL,0
      JZ  EXIT2MC 
      INC DI
      DEC COUNT1
      MOV AL,COUNT1
      CMP AL,0
      JZ  MOVEMC
      JMP LOP1MC
LBL1MC:
MOV AL,MONX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,MONY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROWC
MOV AL,0;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC MONY
JMP CONT2MC


MOVEMC: 
    DEC COUNT2
    MOV AL,14
	MOV COUNT1,AL
    INC MONX
    MOV AL,MONSTEMP
    MOV MONY,AL
    JMP LOP1MC

EXIT2MC:
MOV AX,14
MOV COUNT1,14
MOV COUNT2,14
	
  RET 
  CLEARMONSTERS ENDP
 ;-------CLEARMONSTERS------------------------------
 ;------------GETINPUT------------------------
 GETINPUT PROC 
 
MOV AH,0
INT 16H
RET
GETINPUT ENDP
 ;-------------GETINPUT-------------------------
 
 ;-------------PACMAN-------------------------
 PACMAN PROC 
     MOV DI,OFFSET PACMANGRID
; بردو نفس الفكره 
	  JMP LOP1
  LBL3:
    MOV AL,PACX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,PACY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,0;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC PACY
JMP CONT2 

  LBL4:
    MOV AL,PACX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,PACY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,1;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC PACY
JMP CONT2 
LOP1:
      MOV AL,[DI]
      CMP AL,1
      JZ LBL1
	  CMP AL,2
      JZ LBL2
	  CMP AL,3
	  JZ LBL4
      JMP LBL3	  
CONT2: 

      MOV CL,COUNT2
      CMP CL,0
      JZ  EXIT2 
      INC DI
      DEC COUNT1
      MOV AL,COUNT1
      CMP AL,0
      JZ  MOVE
      JMP LOP1
LBL1:
MOV AL,PACX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,PACY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,14;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC PACY
JMP CONT2

LBL2:
MOV AL,PACX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,PACY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,4;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC PACY
JMP CONT2
MOVE: 
    DEC COUNT2
    MOV AL,14
	MOV COUNT1,AL
    INC PACX
    MOV AL,PACY2
    MOV PACY,AL
    JMP LOP1

EXIT2:
MOV AX,14
MOV COUNT1,14
MOV COUNT2,14
 RET
 PACMAN ENDP
 ;-----------PACMAN------------------------------
   

;-------READPIXEL-------------;
 READPIXEL PROC
 MOV AL,ACTION
 MOV AH,PACX
 MOV TX,AH
 MOV AH,PACY      ; هنا انا باخد ال x,y واشوف الاكشن نوعه ايه و ع اساسه بتشتغل 
 MOV TY,AH
 CMP AL,0
 JZ U
 CMP AL,1
 JZ D
 CMP AL,2
 JZ R
 CMP AL,3
 JZ L
 JMP END1
 L:
 MOV AH,TX     ;EQUATION OF THE LEFT RECTANGLE (X,Y-7,X+14,Y)
 ADD AH,14
 MOV TX3,AH
 
 MOV AH,TY
 MOV TY3,AH
 SUB AH,7
 MOV TY,AH
 
 CALL DETECT
 JMP END1
 R:
MOV AH,TX       ;EQUATION OF THE RIGHT RECTANGLE (X,Y+14,X+14,Y+14+7)
ADD AH,14
MOV TX3,AH
MOV AH,TY
ADD AH,14
MOV TY,AH
ADD AH,7
MOV TY3,AH
CALL DETECT
JMP END1
 U:
                ;EEQUATION OF THE TOP RECTANGLE (X-7,Y,X,Y+14)
 MOV AH,TX
 MOV TX3,AH
 SUB AH,7
 MOV TX,AH 
 MOV AH,TY
 ADD AH,14
 MOV TY3,AH
 CALL DETECT
 JMP END1
 D:
                ;EEQUATION OF THE DOWN RECTANGLE (X+14,Y,X+14+7,Y+14)
 MOV AH,TX
 ADD AH,14
 MOV TX,AH
 ADD AH,7
 MOV TX3,AH
 MOV AH,TY
 ADD AH,14
 MOV TY3,AH
 CALL DETECT ; دي فانكشن بتحدد اللون بتاع البيكسل و لو حاجه من القلوب او الوحش بتخرج 
END1:
RET
READPIXEL ENDP
 ;------READPIXEL---------------;.
 ;------------HORIZONTAL LINE-----------------------
HORIZONTAL PROC
MYLOOP:
    MOV CX,TY1 ;COLUMN
	MOV DX,TX1;ROW
	MOV AL,12 ;PIXEL COLOR
	MOV AH,0CH ;DRAW PIXEL COMMAND
	MOV BH,0
	INT 10H 
	INC TY1
	MOV AX,TY2
	CMP TY1,AX
	JZ EXT
	JMP MYLOOP
EXT:
RET 
HORIZONTAL ENDP	
;-------------HORIZONTAL LINE-----------------------

;-------------VERTICAL------------------
VERTICAL PROC

MYLOOP2:
    MOV CX,TY1 ;COLUMN
	MOV DX,TX1;ROW
	MOV AL,TEMPCOLOR ;PIXEL COLOR
	MOV AH,0CH ;DRAW PIXEL COMMAND
	MOV BH,0
	INT 10H 
	INC TX1
	MOV AX,TX2
	CMP TX1,AX
	JZ EXT2
	JMP MYLOOP2
EXT2:
RET 
VERTICAL ENDP 
;----------------VERTICAL-------------------------

;----------------clearpacman-------------------------
CLEARPACMAN PROC 
 MOV DI,OFFSET PACMANGRID

LOP1C:
      MOV AL,[DI]
      JMP LBL1C	  
CONT2C: 

      MOV CL,COUNT2
      CMP CL,0
      JZ  EXIT2C 
      INC DI
      DEC COUNT1
      MOV AL,COUNT1
      CMP AL,0
      JZ  MOVEC
      JMP LOP1C
LBL1C:
MOV AL,PACX
	MOV AH,0
	MOV TEMP1,AX
	MOV AL,PACY
	MOV TEMP2,AX
	
MOV CX,TEMP2 ;COLUMN
MOV DX,TEMP1;ROW
MOV AL,0;PIXEL COLOR
MOV AH,0CH ;DRAW PIXEL COMMAND
INT 10H
INC PACY
JMP CONT2C

MOVEC: 
    DEC COUNT2
    MOV AL,14
	MOV COUNT1,AL
    INC PACX
    MOV AL,PACY2
    MOV PACY,AL
    JMP LOP1C

EXIT2C:
MOV AX,14
MOV COUNT1,14
MOV COUNT2,14
 RET
 CLEARPACMAN ENDP
 ;--------------------------------
 
 ;---------SETXY------------------------
 SETXY PROC
 MOV AL,PACX
	MOV PACX2,AL            ;هنا انا بحطهم ف TEMP عشان لما اعوزهم تاني
	MOV AL,PACY
	MOV PACY2,AL
	RET
	SETXY ENDP
;---------------------------------------------
 ;---------SETXY2------------------------
 SETXY2 PROC
 MOV AL,PACX2
	MOV PACX,AL           
	MOV AL,PACY2        ;هنا انا برجع الحاجات ال حطيتها 
	MOV PACY,AL
	RET
	SETXY2 ENDP
;--------------------------------------------
 ;---------SETXYM------------------------
 SETXYM PROC
 MOV AL,MONX
	MOV MONX2,AL           ;هنا انا بحطهم ف TEMP عشان لما اعوزهم تاني
	MOV AL,MONY
	MOV MONY2,AL
	MOV MONSTEMP,AL
	RET
	SETXYM ENDP
;---------------------------------------------
 ;---------SETXY2------------------------
 SETXYM2 PROC
 MOV AL,MONX2
	MOV MONX,AL
	MOV AL,MONY2
	MOV MONY,AL                  ;هنا انا برجع الحاجات ال حطيتها 
	MOV MONSTEMP,AL
	RET
	SETXYM2 ENDP
;--------------------------------------------
;-------------DETECT------------------------
DETECT PROC 

;-------ReadPixel-------------;
MOV AL,TY
MOV SAVE ,AL
BACK:
MOV BH,0
 MOV AH,0DH
 MOV CL,TY
 MOV CH,0
 MOV DL,TX
 MOV DH,0  
 INT 10H
 
 CMP AL,1 ;دي لون البوردر
 JZ ENDR
    cmp al,3 ;دي لون الوحش
	CMP AL,4  ; دي الوان القلوب
	JZ ENDR

	CMP AL,10    
	JZ ENDR
	CMP AL,13
	JZ ENDR
	CMP AL,5
	JZ ENDR	
	CMP AL,15
	JZ ENDR	
 INC TY 
 MOV AH,TY3
 CMP AH,TY 
 JNZ BACK
 MOV AH,SAVE 
 MOV TY,AH
 INC TX
 MOV AH,TX3
 CMP AH,TX
 JNZ BACK
 
 ENDR:
RET
DETECT ENDP		
	;--------------------------------
;------------------OPEN RED RECTANGLE-------------------------
OPEN1 PROC 
;94,160,98,180,4
MOV AX,94
MOV TX1,AX
MOV AX,160
MOV TY1,AX
MOV AX,98                        ;دول انا بنقل فيهم الاماكن بتاعت البوكس الاحمر عشان امسحه بالتدريج 
MOV TX2,AX
MOV AX,180
MOV TY2,AX
OPN:
    ;RECTANGLE TX1,TY1,TX2,TY1,0
	MOV AL,0
	MOV TEMPCOLOR,AL    
	CALL VERTICAL   ;هرسم كل شويه خط اسود 
	MOV CX,0FFFFH
DELAY3:
     DEC CX
	 CMP CX,0
	 JNZ DELAY3
	 MOV AX,94
	 MOV TX1,AX
	INC TY1
	MOV AX,TY1
	CMP AX,TY2
	JNZ OPN
RET
OPEN1 ENDP
;-------------------------------------------------------------------
MOVE1 PROC 
 ;115,164
MOV AL,114
MOV MONX,AL
MOV AL,164
MOV MONY,AL
M1:
    CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONX 
	MOV AL,MONX
	CMP AL,75     ;اول مكان المفروض اوصله
	JZ M2        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M1
M2:
    CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONY 
	MOV AL,MONY
	CMP AL,123    ;اول مكان المفروض اوصله
	JZ M3      ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M2
M3:
 CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	INC MONX 
	MOV AL,MONX
	CMP AL,170    ;اول مكان المفروض اوصله
	JZ M4        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M3
M4:
   CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONY 
	MOV AL,MONY
	CMP AL,50    ;اول مكان المفروض اوصله
	JZ M5     ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M4
M5:
 CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONX 
	MOV AL,MONX
	CMP AL,155    ;اول مكان المفروض اوصله
	JZ M6        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M5
M6:
CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONY 
	MOV AL,MONY
	CMP AL,6    ;اول مكان المفروض اوصله
	JZ M7     ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M6
M7:
 CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
RET 
MOVE1 ENDP
;----------------------------MOVE2--------------
MOVE2 PROC 
 ;115,164
MOV AL,114
MOV MONX,AL
MOV AL,145
MOV MONY,AL
M21:
    CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	INC MONY
	MOV AL,MONY
	CMP AL,164     ;اول مكان المفروض اوصله
	JZ M22        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M21
M22:
    CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONX 
	MOV AL,MONX
	CMP AL,75     ;اول مكان المفروض اوصله
	JZ M23        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M22
M23:
CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	INC MONY
	MOV AL,MONY
	CMP AL,205     ;اول مكان المفروض اوصله
	JZ M24        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M23
M24:
CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	INC MONX
	MOV AL,MONX
	CMP AL,83    ;اول مكان المفروض اوصله
	JZ M25        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M24
M25:
CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	INC MONY
	MOV AL,MONY
	CMP AL,229     ;اول مكان المفروض اوصله
	JZ M26        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M25
M26:
CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
RET
MOVE2 ENDP
;-----------------------------MOVE2-------------------------------
;---------------------MOVE3------------------------------------
MOVE3 PROC
 ;115,164
MOV AL,114
MOV MONX,AL
MOV AL,182
MOV MONY,AL
M31:
    CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONY
	MOV AL,MONY
	CMP AL,164     ;اول مكان المفروض اوصله
	JZ M32        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
	
    CALL DELAY
    JMP M31
M32:
CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONX 
	MOV AL,MONX
	CMP AL,75     ;اول مكان المفروض اوصله
	JZ M33        ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M32
M33:
    CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	DEC MONY 
	MOV AL,MONY
	CMP AL,125   ;اول مكان المفروض اوصله
	JZ M34     ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M33
M34:
 CALL SETXYM
	CALL CLEARMONSTERS
	CALL SETXYM2
	INC MONX 
	MOV AL,MONX
	CMP AL,170    ;اول مكان المفروض اوصله
	JZ M35       ;اروح للوب بتاعت تاني مكان
	CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
    CALL DELAY
    JMP M34
M35:
CALL SETXYM
	CALL MONSTERS 
	CALL SETXYM2
RET
MOVE3 ENDP
;--------------------------------SETMONSTER1---------------
SETM1 PROC 
MOV AL,MONX                ;بنقل فيها القيمه بتاعت x,y 
MOV MONSTERX1 ,AL
MOV AH,MONY
MOV MONSTERY1,AH
RET
SETM1 ENDP 
;--------------------------------SETMONSTER1---------------
SETM2 PROC 
MOV AL,MONX
MOV MONSTERX2 ,AL     
MOV AH,MONY              ;بنقل فيها القيمه بتاعت x,y 
MOV MONSTERY2,AH
RET
SETM2 ENDP 
;--------------------------------SETMONSTER1---------------
SETM3 PROC 
MOV AL,MONX                    ;بنقل فيها القيمه بتاعت x,y 
MOV MONSTERX3 ,AL
MOV AH,MONY
MOV MONSTERY3,AH
RET
SETM3 ENDP 
;--------------------------------SETMONSTER1---------------
SETM4 PROC      ;بنقل فيها القيمه بتاعت x,y 
MOV AL,MONX
MOV MONSTERX4 ,AL
MOV AH,MONY
MOV MONSTERY4,AH
RET
SETM4 ENDP 
;-------------------------------DELAY-------------------------------
DELAY PROC 
	MOV CX,0FFFFH
DELAY2:
     DEC CX               ;لووب عشان اعمل ديلاي 
	 CMP CX,0
	 JNZ DELAY2

RET 
DELAY ENDP
;-----------------------------------------------------------
WINP PROC 

mov ah, 9
mov dx, offset WIN
int 21h
RET 
WINP ENDP


;---------------------------
LOSE PROC 

mov ah, 9
mov dx, offset LOST
int 21h
RET 
LOSE ENDP
 END MAIN